name: Remove duplicate operator images
on:
  pull_request:
    types: [ labeled ]
permissions:
  contents: write
jobs:
  run:
    if: ${{ (github.event.label.name == 'operator') }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}
    - name: Remove duplicate operator images
      run: |
        cd operator
        # remove '_#number' at end of filenames
        for file in $(find . -name "*_#*.png"); do
            if [[ "$file" =~ ^(.*)_#([0-9]+)\.png$ ]]; then
                mv "$file" "${BASH_REMATCH[1]}.png"
            fi
        done
    - name: Commit changes
      run: |
        git config user.name "Daniel Su"
        git config user.email "Awedtan@users.noreply.github.com"
        git add .
        git commit -m "Remove duplicate operator images"
        git push
