name: Modify PR assets

on:
  pull_request:
    types: [ labeled ]

jobs:
  run:
    if: ${{ github.event.label.name == 'update' }}
    runs-on: windows-latest

    steps:
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Checkout branch
      uses: actions/checkout@v4
    - name: Download ArkUnpacker
      run: Invoke-WebRequest -Uri "https://github.com/isHarryh/Ark-Unpacker/releases/download/v3.2.0/ArkUnpacker-v3.2.0.exe" -OutFile ArkUnpacker.exe
    - name: List files
      run: Get-ChildItem -Force -Recurse
    - name: Operator spine tranparency
      run: |
        set PYTHONUTF8=1
        set PYTHONIOENCODING=utf-8
        set PYTHONLEGACYWINDOWSSTDIO=utf-8
        .\ArkUnpacker.exe -m "cb" -i "spine/operator" -o "combined/operator"
    - name: Commit changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Operator spine transparency"
        git push
