name: Modify PR assets

on:
  pull_request:
    types: [ labeled ]

jobs:
  run:
    if: ${{ github.event.label.name == 'update' }}
    runs-on: windows-latest

    steps:
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - run: Get-ChildItem -Force -Recurse C:\hostedtoolcache\windows\Python\3.11.9\x64
    - name: Overwrite cp1252.py with utf_8.py
      shell: pwsh
      run: Copy-Item -Path "C:\hostedtoolcache\windows\Python\3.11.9\x64\lib\encodings\utf_8.py" -Destination "C:\hostedtoolcache\windows\Python\3.11.9\x64\lib\encodings\cp1252.py" -Force
    - uses: actions/checkout@v4
    - name: Download ArkUnpacker
      shell: pwsh
      run: Invoke-WebRequest -Uri "https://github.com/isHarryh/Ark-Unpacker/releases/download/v3.2.0/ArkUnpacker-v3.2.0.exe" -OutFile ArkUnpacker.exe
    - name: List files
      shell: pwsh
      run: Get-ChildItem -Force -Recurse
    - name: Operator spine transparency
      shell: pwsh
      run: .\ArkUnpacker.exe -m "cb" -i "spine/operator" -o "combined/operator"
    - name: Commit changes
      shell: pwsh
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Operator spine transparency"
        git push
