name: Modify PR assets

on:
  pull_request:
    types: [ labeled ]

jobs:
  run:
    if: ${{ github.event.label.name == 'update' }}
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Download ArkUnpacker source
      run: git clone --recurse-submodules --depth=1 https://github.com/isHarryh/Ark-Unpacker.git
    - name: Install ArkUnpacker dependencies
      run: pip install bson unitypy numpy pycryptodome flatbuffers
    - name: Patch ArkUnpacker to print UTF-8
      run: (Get-Content ".\Ark-Unpacker\src\utils\GlobalMethods.py") -replace '\{text\}', '{text.encode()}' | Set-Content ".\Ark-Unpacker\src\utils\GlobalMethods.py"
    - name: Set up operator spine inputs
      run: |
        @"
        3
        spine/operator
        combined
        
        
        0
        "@ > "op.txt"
    - name: Apply operator spine transparency
      run: Get-Content op.txt | python .\Ark-Unpacker\Main.py
    - name: Commit changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Operator spine transparency"
        git push
