name: Apply spine transparency
on:
  pull_request:
    types: [ labeled ]
permissions:
  contents: write
jobs:
  run:
    if: ${{ (github.event.label.name == 'spine') }}
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}
    - name: Download ArkUnpacker source
      run: |
        Set-Location ..
        git clone --recurse-submodules --depth=1 https://github.com/isHarryh/Ark-Unpacker.git
    - name: Install ArkUnpacker dependencies
      run: pip install bson unitypy numpy pycryptodome flatbuffers
    - name: Patch ArkUnpacker to encode UTF-8
      run: (Get-Content ..\Ark-Unpacker\src\utils\GlobalMethods.py) -replace '\{text\}', '{text.encode()}' | Set-Content ..\Ark-Unpacker\src\utils\GlobalMethods.py
    - name: Set up operator spine inputs
      run: |
        @"
        3
        spine/operator
        ..\combined\operator
        
        
        0
        "@ > ..\op.txt
    - name: Apply operator spine transparency
      run: Get-Content ..\op.txt | python ..\Ark-Unpacker\Main.py
    - name: Copy over combined operator spines
      run: Copy-Item -Path ..\combined\operator\* -Destination spine/operator -Recurse -Force
    - name: Clean up files
      run: Remove-Item .\ArkUnpackerLogs.log, .\ArkUnpackerConfig.json
    - name: Commit operator spine changes
      run: |
        git config user.name "Daniel Su"
        git config user.email "Awedtan@users.noreply.github.com"
        git add .
        git commit -m "Operator spine transparency"
        git push
    - name: Set up enemy spine inputs
      run: |
        @"
        3
        spine/enemy
        ..\combined\enemy
        
        
        0
        "@ > ..\enemy.txt
    - name: Apply enemy spine transparency
      run: Get-Content ..\enemy.txt | python ..\Ark-Unpacker\Main.py
    - name: Copy over combined enemy spines
      run: Copy-Item -Path ..\combined\enemy\* -Destination spine/enemy -Recurse -Force
    - name: Clean up files
      run: Remove-Item .\ArkUnpackerLogs.log, .\ArkUnpackerConfig.json
    - name: Commit enemy spine changes
      run: |
        git config user.name "Daniel Su"
        git config user.email "Awedtan@users.noreply.github.com"
        git add .
        git commit -m "Enemy spine transparency"
        git push
