name: Resize stage previews
on:
  pull_request:
    types: [ labeled ]
permissions:
  contents: write
jobs:
  run:
    if: ${{ github.event.label.name == 'update' || github.event.label.name == 'stage }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}
    - name: Install ImageMagick
      run: sudo apt install imagemagick
    - name: Resize stage previews
      run: magick mogrify -resize 960x540! ./stages
    - name: Commit changes
      run: |
        git config user.name "Daniel Su"
        git config user.email "Awedtan@users.noreply.github.com"
        git add .
        git commit -m "Resize stage previews"
        git push
