name: Update assets

on:
  workflow_dispatch:
    inputs:
      specific_downloads:
        description: 'Specific ABs to download'
        required: false
        default: ''
  schedule:
    - cron:  '0 */6 * * *'

permissions:
  contents: write

jobs:
  update:
    name: Update assets
    strategy:
      fail-fast: false
      matrix:
        server: [cn, en]
    uses: ./.github/workflows/workflow.yml
    secrets: inherit
    with:
      server: ${{ matrix.server }}
      specific_downloads: ${{ github.event.inputs.specific_downloads }}
