name: Update assets

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 * * * *'

permissions:
  contents: write

jobs:
  update:
    name: Update assets
    strategy:
      fail-fast: false
      matrix:
        server: [cn, en]
    uses: ./.github/workflows/workflow.yml
    secrets: inherit
    with:
      server: ${{ matrix.server }}
