name: Update assets

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  update:
    name: Update assets
    strategy:
      fail-fast: false
      matrix:
        server: [cn, en]
    uses: ./.github/workflows/update-workflow.yml
    secrets: inherit
    with:
      server: ${{ matrix.server }}
