name: Update assets

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 * * * *'

permissions:
  contents: write

jobs:
  update:
    strategy:
      matrix:
        server: [cn, en]
    uses: ./.github/workflows/workflow.yml
    with:
      server: ${{ matrix.server }}
